name = "mcp-weather"
main = "src/index.ts"
compatibility_date = "2025-04-17"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "WeatherMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WeatherMCP"]

[[routes]]
pattern = "weathermcp.haerttrich.dev"
custom_domain = true
